isLocal: false
localToken: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjUyNTM4MDBlLWYzZGEtNDVhYS1hODZhLTBjNjZmYzVjMDEzOCIsImlhdCI6MTYyMTE2MjA2Niwic3ViIjoiZGV2ZWxvcGVyL2M0MWNmYzkyLTNmMzktYThiMC0xM2UxLTkwMmRjNjE4NWRkNSIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjQ1LjY0LjE0NS45NSJdLCJ0eXBlIjoiY2xpZW50In1dfQ.mx1sqjs4FjHVkVV63zKTWfnCAj_Xw7j844RZAawLAuTg1iot8OSlkWsrfGJPmlIg8deZBlp97W6zNsAPm8HMXA"
serverToken: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImU4YjVhMDgxLTJjOGMtNDY0NS04ZjYxLTRkNTc1ZjQ1MDVkMiIsImlhdCI6MTYyNTQ3MTI4Nywic3ViIjoiZGV2ZWxvcGVyL2M0MWNmYzkyLTNmMzktYThiMC0xM2UxLTkwMmRjNjE4NWRkNSIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjQ5LjUwLjE2Mi41NCJdLCJ0eXBlIjoiY2xpZW50In1dfQ.cunup91ccUCrPXzHWjmcdVxoaiCJB1sU8j23tAteTfVgvQg8eUV07Q7XHCOMDmszntG6FgYi9d0eDAiNw6afZg"

dbHost: localhost
dbPort: 3306
dbUser: root
dbPassword:
dbSchema: kalba
mysqlMinConnection: 1
mysqlMaxConnection: 5000