isLocal: true
localToken: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6Ijc3OTVhODAxLWFmYjgtNGUyOC05Y2MwLTVhZTU3MjFjZjdiMSIsImlhdCI6MTYyOTM3MTAxNywic3ViIjoiZGV2ZWxvcGVyL2M0MWNmYzkyLTNmMzktYThiMC0xM2UxLTkwMmRjNjE4NWRkNSIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjQ1LjY0LjE0NS4xMzYiXSwidHlwZSI6ImNsaWVudCJ9XX0.Y7R1NBQ7NCSNtiuxxRCVJDaTn9uTfMMLNYV_p0a4gnfxx0ZgjfqPLHh-SstGYovaMBPNGltsAEO85hdXbDnC-A"
serverToken: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImU4YjVhMDgxLTJjOGMtNDY0NS04ZjYxLTRkNTc1ZjQ1MDVkMiIsImlhdCI6MTYyNTQ3MTI4Nywic3ViIjoiZGV2ZWxvcGVyL2M0MWNmYzkyLTNmMzktYThiMC0xM2UxLTkwMmRjNjE4NWRkNSIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjQ5LjUwLjE2Mi41NCJdLCJ0eXBlIjoiY2xpZW50In1dfQ.cunup91ccUCrPXzHWjmcdVxoaiCJB1sU8j23tAteTfVgvQg8eUV07Q7XHCOMDmszntG6FgYi9d0eDAiNw6afZg"

quizAnswer:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 1
  - 2
  - 3
  - 4,5
  - 1,2,3,4,5