server:
  port: 8484

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: kalba
  jwt:
    secret: potiondev

coc:
  token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6ImE1NDY2YTg3LTYyODMtNDRhOS04NTlkLTRlOGYwZTQ4YjVhMiIsImlhdCI6MTY2NzExNzU0NSwic3ViIjoiZGV2ZWxvcGVyL2M0MWNmYzkyLTNmMzktYThiMC0xM2UxLTkwMmRjNjE4NWRkNSIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjEzLjIwOS44OS4xNSIsIjIxOC4yMzcuMTgwLjQzIl0sInR5cGUiOiJjbGllbnQifV19.zORcNzzgi0aAul1Z9BKtq8tEjvtLSG8NEfjFUhyD1Qtnw2h1FcsmyTloJpI8xBKhT0rmDnXs61jkrGr3CTUq6g
